!=======================================================================
! Generated by: PSCAD v5.0.0.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Current_Limiter_3_1
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Current_Limiter_3_1Dyn(Iqout, Idout, Iqin, Idin,       &
     &   Theta)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
      REAL    LIMIT         ! Hard Limiter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Iqin, Idin, Theta
      REAL,    INTENT(OUT) :: Iqout, Idout

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5
      REAL     Thetaint, RT_6, RT_7, RT_8, RT_9
      REAL     RT_10, RT_11, RT_12, RT_13, RT_14
      REAL     RT_15

! Internal Variables
      LOGICAL  LVD1_1
      REAL     RVD2_1(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 21
      IPGB      = NPGB
      NPGB      = NPGB + 1
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Iqout    = STOF(ISTOF + 1)
      Idout    = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 6)
      RT_2     = STOF(ISTOF + 7)
      RT_3     = STOF(ISTOF + 8)
      RT_4     = STOF(ISTOF + 9)
      RT_5     = STOF(ISTOF + 10)
      Thetaint = STOF(ISTOF + 11)
      RT_6     = STOF(ISTOF + 12)
      RT_7     = STOF(ISTOF + 13)
      RT_8     = STOF(ISTOF + 14)
      RT_9     = STOF(ISTOF + 15)
      RT_10    = STOF(ISTOF + 16)
      RT_11    = STOF(ISTOF + 17)
      RT_12    = STOF(ISTOF + 18)
      RT_13    = STOF(ISTOF + 19)
      RT_14    = STOF(ISTOF + 20)
      RT_15    = STOF(ISTOF + 21)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Current_Limiter_3_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[square] Square 
      RT_1 = Idin * Idin

! 40:[square] Square 
      RT_2 = Iqin * Iqin

! 50:[const] Real Constant 
      RT_14 = -1.0

! 60:[const] Real Constant 
      RT_15 = 1.0

! 70:[ATAN_3_1]  
Thetaint=ATAN2(Idin,Iqin)

! 80:[abs] Absolute Value 
      RT_11 = ABS(Thetaint)

! 90:[pgb] Output Channel 'Thetaint'

      PGB(IPGB+1) = RT_11

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_12 = PI_BY2

! 120:[trig] Trigonometric Functions 
!  Trig-Func
      RT_5 = SIN(Thetaint)
!

! 130:[sumjct] Summing/Differencing Junctions 
      RT_3 = + RT_1 + RT_2

! 140:[sqrt] Square Root 
      LVD1_1 = STORL(NSTORL)
      IF (RT_3 .LT. 0.0) THEN
        RT_4 = 0.0
        IF (.NOT. LVD1_1) THEN
          CALL EMTDC_MESSAGE(ICALL_NO,1352605656,1,2,"A negative value i&
     &s detected as an input to the Square Root function. ")
          CALL EMTDC_MESSAGE(ICALL_NO,1352605656,1,-1,"Input is treated &
     &as 0.0.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ELSE
         RT_4 = SQRT(RT_3)
      ENDIF
      NSTORL = NSTORL + 1

! 150:[trig] Trigonometric Functions 
!  Trig-Func
      RT_6 = COS(Thetaint)
!

! 160:[compar] Two Input Comparator 
!
      CALL EMTDC_X2COMP(0,0,RT_11,RT_12,1.0,0.0,0.0,RVD2_1)
      RT_13 = RVD2_1(1)

! 170:[select] Two Input Selector 
      IF (NINT(RT_13) .EQ. RTCI(NRTCI)) THEN
         RT_10 = RT_14
      ELSE
         RT_10 = RT_15
      ENDIF
      NRTCI = NRTCI + 1
!

! 180:[mult] Multiplier 
      RT_8 = RT_4 * RT_10

! 190:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (-3.0e+20 .LE. 3.0e+20) THEN
        RT_9 = LIMIT(-3.0e+20, 3.0e+20, RT_8)
      ELSE
        RT_9 = RT_8
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,357236606,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 200:[abs] Absolute Value 
      RT_7 = ABS(RT_9)

! 210:[mult] Multiplier 
      Iqout = RT_6 * RT_7

! 220:[mult] Multiplier 
      Idout = RT_5 * RT_7

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Iqout
      STOF(ISTOF + 2) = Idout
      STOF(ISTOF + 3) = Iqin
      STOF(ISTOF + 4) = Idin
      STOF(ISTOF + 5) = Theta
      STOF(ISTOF + 6) = RT_1
      STOF(ISTOF + 7) = RT_2
      STOF(ISTOF + 8) = RT_3
      STOF(ISTOF + 9) = RT_4
      STOF(ISTOF + 10) = RT_5
      STOF(ISTOF + 11) = Thetaint
      STOF(ISTOF + 12) = RT_6
      STOF(ISTOF + 13) = RT_7
      STOF(ISTOF + 14) = RT_8
      STOF(ISTOF + 15) = RT_9
      STOF(ISTOF + 16) = RT_10
      STOF(ISTOF + 17) = RT_11
      STOF(ISTOF + 18) = RT_12
      STOF(ISTOF + 19) = RT_13
      STOF(ISTOF + 20) = RT_14
      STOF(ISTOF + 21) = RT_15


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Iqout    is output
      !Idout    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Current_Limiter_3_1Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_12, RT_14, RT_15

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 1
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_12    = STOF(ISTOF + 18)
      RT_14    = STOF(ISTOF + 20)
      RT_15    = STOF(ISTOF + 21)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Current_Limiter_3_1.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 

      RT_14 = -1.0

! 60:[const] Real Constant 

      RT_15 = 1.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_12 = PI_BY2

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 18) = RT_12
      STOF(ISTOF + 20) = RT_14
      STOF(ISTOF + 21) = RT_15


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Current_Limiter_3_1Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_12, RT_14, RT_15

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[square] Square 

! 40:[square] Square 

! 50:[const] Real Constant 
      RT_14 = -1.0

! 60:[const] Real Constant 
      RT_15 = 1.0

! 70:[ATAN_3_1]  

! 80:[abs] Absolute Value 

! 90:[pgb] Output Channel 'Thetaint'

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_12 = PI_BY2

! 120:[trig] Trigonometric Functions 

! 130:[sumjct] Summing/Differencing Junctions 

! 140:[sqrt] Square Root 

! 150:[trig] Trigonometric Functions 

! 160:[compar] Two Input Comparator 

! 170:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 180:[mult] Multiplier 

! 190:[hardlimit] Hard Limiter 

! 200:[abs] Absolute Value 

! 210:[mult] Multiplier 

! 220:[mult] Multiplier 

      RETURN
      END

!=======================================================================

      SUBROUTINE Current_Limiter_3_1Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_12, RT_14, RT_15

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_14 = -1.0

! 60:[const] Real Constant 
      RT_15 = 1.0

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_12 = PI_BY2

      RETURN
      END

