!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : PQ_control_10_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE PQ_control_10_2Dyn(UFqref, W, Wref, Qref, Pref, Qmeas, &
     &   Pmeas, KpP, KiP, Kq, Vpccref, Controlmode, Vpccmeas, Wmeas,    &
     &   Qcontrol, H, D, VratedLLrms, w0)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Wref, Qref, Pref
      REAL,    INTENT(IN)  :: Qmeas, Pmeas, KpP
      REAL,    INTENT(IN)  :: KiP, Kq, Vpccref
      REAL,    INTENT(IN)  :: Controlmode
      REAL,    INTENT(IN)  :: Vpccmeas, Wmeas
      REAL,    INTENT(IN)  :: Qcontrol, H, D
      REAL,    INTENT(IN)  :: VratedLLrms, w0
      REAL,    INTENT(OUT) :: UFqref, W

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, RT_16
      REAL     RT_17, RT_18

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 37
      IPGB      = NPGB
      NPGB      = NPGB + 2
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      UFqref   = STOF(ISTOF + 1)
      W        = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 20)
      RT_2     = STOF(ISTOF + 21)
      RT_3     = STOF(ISTOF + 22)
      RT_4     = STOF(ISTOF + 23)
      RT_5     = STOF(ISTOF + 24)
      RT_6     = STOF(ISTOF + 25)
      RT_7     = STOF(ISTOF + 26)
      RT_8     = STOF(ISTOF + 27)
      RT_9     = STOF(ISTOF + 28)
      RT_10    = STOF(ISTOF + 29)
      RT_11    = STOF(ISTOF + 30)
      RT_12    = STOF(ISTOF + 31)
      RT_13    = STOF(ISTOF + 32)
      RT_14    = STOF(ISTOF + 33)
      RT_15    = STOF(ISTOF + 34)
      RT_16    = STOF(ISTOF + 35)
      RT_17    = STOF(ISTOF + 36)
      RT_18    = STOF(ISTOF + 37)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PQ_control_10_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_15 = 0.0

! 80:[const] Real Constant 
      RT_16 = 1.0

! 200:[const] Real Constant 
      RT_3 = 0.0

! 290:[gain] Gain Block 
!  Gain
      RT_18 = 2.0 * H

! 320:[const] Real Constant 
      RT_5 = 0.0

! 350:[const] Real Constant 
      RT_17 = 0.0

! 360:[sumjct] Summing/Differencing Junctions 
      RT_1 = + Qref - Qmeas

! 370:[mult] Multiplier 
      RT_8 = RT_1 * Kq

! 380:[select] Two Input Selector 
      IF (NINT(Qcontrol) .EQ. RTCI(NRTCI)) THEN
         RT_14 = RT_1
      ELSE
         RT_14 = RT_15
      ENDIF
      NRTCI = NRTCI + 1
!

! 390:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_14
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_13 = EMTDC_XINT(0, 0, 0, RVD1_1, 100.0, 0.0, -1.0e+20, 1.0e+20,&
     & RVD2_2, RVD2_1)

! 400:[sumjct] Summing/Differencing Junctions 
      RT_4 = + RT_8 + RT_13

! 410:[select] Two Input Selector 
      IF (NINT(Controlmode) .EQ. RTCI(NRTCI)) THEN
         RT_2 = RT_3
      ELSE
         RT_2 = RT_4
      ENDIF
      NRTCI = NRTCI + 1
!

! 420:[sumjct] Summing/Differencing Junctions 
      RT_11 = + Pref - Pmeas - RT_10

! 430:[div] Divider 
      IF (ABS(RT_18) .LT. 1.0E-100) THEN
         IF (RT_18 .LT. 0.0)  THEN
            RT_12 = -1.0E100 * RT_11
         ELSE
            RT_12 =  1.0E100 * RT_11
         ENDIF
      ELSE
         RT_12 = RT_11 / RT_18
      ENDIF

! 440:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_12
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_9 = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+20, 1.0e+20, RV&
     &D2_2, RVD2_1)

! 450:[gain] Gain Block 
!  Gain
      RT_10 = D * RT_9

! 460:[mult] Multiplier 
      RT_6 = RT_9 * KpP

! 470:[select] Two Input Selector 
      IF (NINT(Controlmode) .EQ. RTCI(NRTCI)) THEN
         RT_7 = RT_5
      ELSE
         RT_7 = RT_6
      ENDIF
      NRTCI = NRTCI + 1
!

! 480:[sumjct] Summing/Differencing Junctions 
      W = + RT_7 + Wref

! 490:[sumjct] Summing/Differencing Junctions 
      UFqref = + RT_2 + Vpccref

! 500:[pgb] Output Channel 'Wint'

      PGB(IPGB+1) = RT_9

! 530:[pgb] Output Channel 'UFqref'

      PGB(IPGB+2) = UFqref

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = UFqref
      STOF(ISTOF + 2) = W
      STOF(ISTOF + 3) = Wref
      STOF(ISTOF + 4) = Qref
      STOF(ISTOF + 5) = Pref
      STOF(ISTOF + 6) = Qmeas
      STOF(ISTOF + 7) = Pmeas
      STOF(ISTOF + 8) = KpP
      STOF(ISTOF + 9) = KiP
      STOF(ISTOF + 10) = Kq
      STOF(ISTOF + 11) = Vpccref
      STOF(ISTOF + 12) = Controlmode
      STOF(ISTOF + 13) = Vpccmeas
      STOF(ISTOF + 14) = Wmeas
      STOF(ISTOF + 15) = Qcontrol
      STOF(ISTOF + 16) = H
      STOF(ISTOF + 17) = D
      STOF(ISTOF + 18) = VratedLLrms
      STOF(ISTOF + 19) = w0
      STOF(ISTOF + 20) = RT_1
      STOF(ISTOF + 21) = RT_2
      STOF(ISTOF + 22) = RT_3
      STOF(ISTOF + 23) = RT_4
      STOF(ISTOF + 24) = RT_5
      STOF(ISTOF + 25) = RT_6
      STOF(ISTOF + 26) = RT_7
      STOF(ISTOF + 27) = RT_8
      STOF(ISTOF + 28) = RT_9
      STOF(ISTOF + 29) = RT_10
      STOF(ISTOF + 30) = RT_11
      STOF(ISTOF + 31) = RT_12
      STOF(ISTOF + 32) = RT_13
      STOF(ISTOF + 33) = RT_14
      STOF(ISTOF + 34) = RT_15
      STOF(ISTOF + 35) = RT_16
      STOF(ISTOF + 36) = RT_17
      STOF(ISTOF + 37) = RT_18


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !UFqref   is output
      !W        is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PQ_control_10_2Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_5, RT_15, RT_16, RT_17

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 2
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_3     = STOF(ISTOF + 22)
      RT_5     = STOF(ISTOF + 24)
      RT_15    = STOF(ISTOF + 34)
      RT_16    = STOF(ISTOF + 35)
      RT_17    = STOF(ISTOF + 36)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PQ_control_10_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 

      RT_15 = 0.0

! 80:[const] Real Constant 

      RT_16 = 1.0

! 200:[const] Real Constant 

      RT_3 = 0.0

! 320:[const] Real Constant 

      RT_5 = 0.0

! 350:[const] Real Constant 

      RT_17 = 0.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 22) = RT_3
      STOF(ISTOF + 24) = RT_5
      STOF(ISTOF + 34) = RT_15
      STOF(ISTOF + 35) = RT_16
      STOF(ISTOF + 36) = RT_17


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PQ_control_10_2Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_5, RT_15, RT_16, RT_17

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_15 = 0.0

! 80:[const] Real Constant 
      RT_16 = 1.0

! 200:[const] Real Constant 
      RT_3 = 0.0

! 290:[gain] Gain Block 

! 320:[const] Real Constant 
      RT_5 = 0.0

! 350:[const] Real Constant 
      RT_17 = 0.0

! 360:[sumjct] Summing/Differencing Junctions 

! 370:[mult] Multiplier 

! 380:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 390:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 400:[sumjct] Summing/Differencing Junctions 

! 410:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 420:[sumjct] Summing/Differencing Junctions 

! 430:[div] Divider 

! 440:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 450:[gain] Gain Block 

! 460:[mult] Multiplier 

! 470:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 480:[sumjct] Summing/Differencing Junctions 

! 490:[sumjct] Summing/Differencing Junctions 

! 500:[pgb] Output Channel 'Wint'

! 530:[pgb] Output Channel 'UFqref'

      RETURN
      END

!=======================================================================

      SUBROUTINE PQ_control_10_2Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_3, RT_5, RT_15, RT_16, RT_17

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[const] Real Constant 
      RT_15 = 0.0

! 80:[const] Real Constant 
      RT_16 = 1.0

! 200:[const] Real Constant 
      RT_3 = 0.0

! 320:[const] Real Constant 
      RT_5 = 0.0

! 350:[const] Real Constant 
      RT_17 = 0.0

      RETURN
      END

