!=======================================================================
! Generated by: PSCAD v5.0.0.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : VF_Control_7_2_2
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE VF_Control_7_2_2Dyn(Vref, Igrid, Vgrid, I_inv, W,      &
     &   UFqref, Wgrid, Pdq, Qdq, Wref, VratedLLrms, Iratedphrms,       &
     &   Wrated, Lf, Cf)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'
!     SUBR    TRDQO         ! DQ0 transformation
      REAL    EMTDC_XPI     ! 'Proportional-Integral Controller /w Interpolation'
!     SUBR    Current_Limiter_3_2_2Dyn  ! 
      REAL    REALPOLE      ! Real Pole

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Igrid(3), Vgrid(3)
      REAL,    INTENT(IN)  :: I_inv(3), W, UFqref
      REAL,    INTENT(IN)  :: Wref, VratedLLrms
      REAL,    INTENT(IN)  :: Iratedphrms, Wrated
      REAL,    INTENT(IN)  :: Lf, Cf
      REAL,    INTENT(OUT) :: Vref(3), Wgrid, Pdq
      REAL,    INTENT(OUT) :: Qdq

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     Err, RT_7, RT_8, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, RT_14, RT_15
      REAL     Ucd, RT_16, Ucq, RT_17, RT_18
      REAL     RT_19, RT_20(3), RT_21, RT_22
      REAL     RT_23, RT_24, RT_25, RT_26, RT_27
      REAL     RT_28, RT_29, RT_30, RT_31, RT_32
      REAL     RT_33, RT_34, RT_35, RT_36
      REAL     Delta_Vc, RT_37, RT_38, Theta_ref
      REAL     RT_39, RT_40, RT_41, RT_42
      REAL     Delta_Vf, RT_43, RT_44, RT_45
      REAL     RT_46, UFq, UFd, ISq, ISd, Theta
      REAL     RT_47, RT_48, RT_49, RT_50
      REAL     RT_51(3), RT_52(3), Vbase
      REAL     RT_53(3), Ibase, RT_54, RT_55
      REAL     RT_56, RT_57, RT_58, MVAbase
      REAL     wLf_pu, RT_59, RT_60, wCf_pu
      REAL     Zbase, RT_61, RT_62, Cbase, RT_63
      REAL     RT_64, RT_65, RT_66, RT_67, RT_68
      REAL     RT_69, RT_70, RT_71, RT_72, RT_73
      REAL     RT_74, RT_75, KpI, TiI, RT_76
      REAL     RT_77, KpV, RT_78, RT_79, TiV
      REAL     RT_80, RT_81, RT_82, RT_83, RT_84
      REAL     Iout, IWd, IWq, Lbase

! Internal Variables
      LOGICAL  LVD1_1
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 141
      IPGB      = NPGB
      NPGB      = NPGB + 22
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Wgrid    = STOF(ISTOF + 15)
      Pdq      = STOF(ISTOF + 16)
      Qdq      = STOF(ISTOF + 17)
      RT_1     = STOF(ISTOF + 24)
      RT_2     = STOF(ISTOF + 25)
      RT_3     = STOF(ISTOF + 26)
      RT_4     = STOF(ISTOF + 27)
      RT_5     = STOF(ISTOF + 28)
      RT_6     = STOF(ISTOF + 29)
      Err      = STOF(ISTOF + 30)
      RT_7     = STOF(ISTOF + 31)
      RT_8     = STOF(ISTOF + 32)
      RT_9     = STOF(ISTOF + 33)
      RT_10    = STOF(ISTOF + 34)
      RT_11    = STOF(ISTOF + 35)
      RT_12    = STOF(ISTOF + 36)
      RT_13    = STOF(ISTOF + 37)
      RT_14    = STOF(ISTOF + 38)
      RT_15    = STOF(ISTOF + 39)
      Ucd      = STOF(ISTOF + 40)
      RT_16    = STOF(ISTOF + 41)
      Ucq      = STOF(ISTOF + 42)
      RT_17    = STOF(ISTOF + 43)
      RT_18    = STOF(ISTOF + 44)
      RT_19    = STOF(ISTOF + 45)
      RT_21    = STOF(ISTOF + 49)
      RT_22    = STOF(ISTOF + 50)
      RT_23    = STOF(ISTOF + 51)
      RT_24    = STOF(ISTOF + 52)
      RT_25    = STOF(ISTOF + 53)
      RT_26    = STOF(ISTOF + 54)
      RT_27    = STOF(ISTOF + 55)
      RT_28    = STOF(ISTOF + 56)
      RT_29    = STOF(ISTOF + 57)
      RT_30    = STOF(ISTOF + 58)
      RT_31    = STOF(ISTOF + 59)
      RT_32    = STOF(ISTOF + 60)
      RT_33    = STOF(ISTOF + 61)
      RT_34    = STOF(ISTOF + 62)
      RT_35    = STOF(ISTOF + 63)
      RT_36    = STOF(ISTOF + 64)
      Delta_Vc = STOF(ISTOF + 65)
      RT_37    = STOF(ISTOF + 66)
      RT_38    = STOF(ISTOF + 67)
      Theta_ref = STOF(ISTOF + 68)
      RT_39    = STOF(ISTOF + 69)
      RT_40    = STOF(ISTOF + 70)
      RT_41    = STOF(ISTOF + 71)
      RT_42    = STOF(ISTOF + 72)
      Delta_Vf = STOF(ISTOF + 73)
      RT_43    = STOF(ISTOF + 74)
      RT_44    = STOF(ISTOF + 75)
      RT_45    = STOF(ISTOF + 76)
      RT_46    = STOF(ISTOF + 77)
      UFq      = STOF(ISTOF + 78)
      UFd      = STOF(ISTOF + 79)
      ISq      = STOF(ISTOF + 80)
      ISd      = STOF(ISTOF + 81)
      Theta    = STOF(ISTOF + 82)
      RT_47    = STOF(ISTOF + 83)
      RT_48    = STOF(ISTOF + 84)
      RT_49    = STOF(ISTOF + 85)
      RT_50    = STOF(ISTOF + 86)
      Vbase    = STOF(ISTOF + 93)
      Ibase    = STOF(ISTOF + 97)
      RT_54    = STOF(ISTOF + 98)
      RT_55    = STOF(ISTOF + 99)
      RT_56    = STOF(ISTOF + 100)
      RT_57    = STOF(ISTOF + 101)
      RT_58    = STOF(ISTOF + 102)
      MVAbase  = STOF(ISTOF + 103)
      wLf_pu   = STOF(ISTOF + 104)
      RT_59    = STOF(ISTOF + 105)
      RT_60    = STOF(ISTOF + 106)
      wCf_pu   = STOF(ISTOF + 107)
      Zbase    = STOF(ISTOF + 108)
      RT_61    = STOF(ISTOF + 109)
      RT_62    = STOF(ISTOF + 110)
      Cbase    = STOF(ISTOF + 111)
      RT_63    = STOF(ISTOF + 112)
      RT_64    = STOF(ISTOF + 113)
      RT_65    = STOF(ISTOF + 114)
      RT_66    = STOF(ISTOF + 115)
      RT_67    = STOF(ISTOF + 116)
      RT_68    = STOF(ISTOF + 117)
      RT_69    = STOF(ISTOF + 118)
      RT_70    = STOF(ISTOF + 119)
      RT_71    = STOF(ISTOF + 120)
      RT_72    = STOF(ISTOF + 121)
      RT_73    = STOF(ISTOF + 122)
      RT_74    = STOF(ISTOF + 123)
      RT_75    = STOF(ISTOF + 124)
      KpI      = STOF(ISTOF + 125)
      TiI      = STOF(ISTOF + 126)
      RT_76    = STOF(ISTOF + 127)
      RT_77    = STOF(ISTOF + 128)
      KpV      = STOF(ISTOF + 129)
      RT_78    = STOF(ISTOF + 130)
      RT_79    = STOF(ISTOF + 131)
      TiV      = STOF(ISTOF + 132)
      RT_80    = STOF(ISTOF + 133)
      RT_81    = STOF(ISTOF + 134)
      RT_82    = STOF(ISTOF + 135)
      RT_83    = STOF(ISTOF + 136)
      RT_84    = STOF(ISTOF + 137)
      Iout     = STOF(ISTOF + 138)
      IWd      = STOF(ISTOF + 139)
      IWq      = STOF(ISTOF + 140)
      Lbase    = STOF(ISTOF + 141)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vref(IT_0) = STOF(ISTOF + 0 + IT_0)
         RT_20(IT_0) = STOF(ISTOF + 45 + IT_0)
         RT_51(IT_0) = STOF(ISTOF + 86 + IT_0)
         RT_52(IT_0) = STOF(ISTOF + 89 + IT_0)
         RT_53(IT_0) = STOF(ISTOF + 93 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'VF_Control_7_2_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[emtconst] Commonly Used Constants (pi...) 
      RT_45 = PI_BY2

! 30:[const] Real Constant 
      RT_36 = 0.0

! 40:[const] Real Constant 
      RT_81 = 0.0

! 70:[const] Real Constant 
      RT_44 = 0.0

! 90:[const] Real Constant 
      RT_8 = 0.0

! 110:[const] Real Constant 
      RT_46 = 0.0

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_40 = PI_BY2

! 130:[const] Real Constant 
      RT_11 = 0.0

! 180:[emtconst] Commonly Used Constants (pi...) 
      RT_50 = SQRT_3

! 190:[emtconst] Commonly Used Constants (pi...) 
      RT_49 = SQRT_2

! 200:[const] Real Constant 
      RT_80 = 1.0

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_47 = SQRT_2

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_37 = TWO_PI

! 280:[const] Real Constant 
      RT_59 = 1.0

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_57 = SQRT_3

! 320:[const] Real Constant 
      KpI = 5.0

! 330:[const] Real Constant 
      RT_23 = 1.0

! 340:[const] Real Constant 
      KpV = 1.0

! 350:[const] Real Constant 
      RT_76 = 1.0

! 360:[const] Real Constant 
      RT_79 = 1.0

! 370:[const] Real Constant 
      RT_77 = 5.0

! 380:[const] Real Constant 
      RT_78 = 10.0

! 390:[const] Real Constant 
      RT_22 = 1.0

! 430:[const] Real Constant 
      RT_63 = 1.0

! 450:[gain] Gain Block 
!  Gain
      Wgrid = Wrated * W

! 460:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = Wgrid
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Theta = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+22, 1.0e+22, R&
     &VD2_2, RVD2_1)

! 470:[div] Divider 
      IF (ABS(RT_50) .LT. 1.0E-100) THEN
         IF (RT_50 .LT. 0.0)  THEN
            RT_48 = -1.0E100 * VratedLLrms
         ELSE
            RT_48 =  1.0E100 * VratedLLrms
         ENDIF
      ELSE
         RT_48 = VratedLLrms / RT_50
      ENDIF

! 480:[mult] Multiplier 
      Vbase = RT_48 * RT_49

! 490:[square] Square 
      RT_58 = VratedLLrms * VratedLLrms

! 500:[mult] Multiplier 
      Ibase = Iratedphrms * RT_47

! 510:[mult] Multiplier 
      RT_38 = Wref * RT_37

! 520:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_38
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      Theta_ref = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+22, 1.0e+2&
     &2, RVD2_2, RVD2_1)

! 530:[mult] Multiplier 
      RT_56 = VratedLLrms * Iratedphrms

! 540:[mult] Multiplier 
      MVAbase = RT_56 * RT_57

! 550:[div] Divider 
      IF (ABS(RT_77) .LT. 1.0E-100) THEN
         IF (RT_77 .LT. 0.0)  THEN
            TiI = -1.0E100 * RT_76
         ELSE
            TiI =  1.0E100 * RT_76
         ENDIF
      ELSE
         TiI = RT_76 / RT_77
      ENDIF

! 560:[div] Divider 
      IF (ABS(RT_78) .LT. 1.0E-100) THEN
         IF (RT_78 .LT. 0.0)  THEN
            TiV = -1.0E100 * RT_79
         ELSE
            TiV =  1.0E100 * RT_79
         ENDIF
      ELSE
         TiV = RT_79 / RT_78
      ENDIF

! 570:[gain] Gain Block 
!  Gain
      RT_54 = Wrated * Lf

! 580:[gain] Gain Block 
!  Gain
      RT_55 = Wrated * Cf

! 590:[div] Divider 
      IF (ABS(Ibase) .LT. 1.0E-100) THEN
         IF (Ibase .LT. 0.0)  THEN
            RT_51 = -1.0E100 * I_inv
         ELSE
            RT_51 =  1.0E100 * I_inv
         ENDIF
      ELSE
         RT_51 = I_inv / Ibase
      ENDIF

! 600:[datatap] Scalar/Array Tap 
      RT_64 = RT_51(1)

! 610:[datatap] Scalar/Array Tap 
      RT_65 = RT_51(2)

! 620:[datatap] Scalar/Array Tap 
      RT_66 = RT_51(3)

! 630:[div] Divider 
      IF (ABS(Vbase) .LT. 1.0E-100) THEN
         IF (Vbase .LT. 0.0)  THEN
            RT_52 = -1.0E100 * Vgrid
         ELSE
            RT_52 =  1.0E100 * Vgrid
         ENDIF
      ELSE
         RT_52 = Vgrid / Vbase
      ENDIF

! 640:[datatap] Scalar/Array Tap 
      RT_68 = RT_52(1)

! 650:[datatap] Scalar/Array Tap 
      RT_69 = RT_52(2)

! 660:[datatap] Scalar/Array Tap 
      RT_70 = RT_52(3)

! 670:[div] Divider 
      IF (ABS(Ibase) .LT. 1.0E-100) THEN
         IF (Ibase .LT. 0.0)  THEN
            RT_53 = -1.0E100 * Igrid
         ELSE
            RT_53 =  1.0E100 * Igrid
         ENDIF
      ELSE
         RT_53 = Igrid / Ibase
      ENDIF

! 680:[datatap] Scalar/Array Tap 
      RT_72 = RT_53(1)

! 690:[datatap] Scalar/Array Tap 
      RT_73 = RT_53(2)

! 700:[datatap] Scalar/Array Tap 
      RT_74 = RT_53(3)

! 710:[div] Divider 
      IF (ABS(MVAbase) .LT. 1.0E-100) THEN
         IF (MVAbase .LT. 0.0)  THEN
            Zbase = -1.0E100 * RT_58
         ELSE
            Zbase =  1.0E100 * RT_58
         ENDIF
      ELSE
         Zbase = RT_58 / MVAbase
      ENDIF

! 720:[mult] Multiplier 
      RT_60 = Wrated * Zbase

! 730:[div] Divider 
      IF (ABS(Zbase) .LT. 1.0E-100) THEN
         IF (Zbase .LT. 0.0)  THEN
            wLf_pu = -1.0E100 * RT_54
         ELSE
            wLf_pu =  1.0E100 * RT_54
         ENDIF
      ELSE
         wLf_pu = RT_54 / Zbase
      ENDIF

! 740:[mult] Multiplier 
      wCf_pu = RT_55 * Zbase

! 750:[abcdq0] abc dq0 transformation 
!ABC to DQ0 transformation
      CALL TRDQO(RT_64,RT_65,RT_66,IWd,IWq,RT_67,Theta,1)

! 760:[abcdq0] abc dq0 transformation 
!ABC to DQ0 transformation
      CALL TRDQO(RT_68,RT_69,RT_70,UFd,UFq,RT_71,Theta,1)

! 770:[abcdq0] abc dq0 transformation 
!ABC to DQ0 transformation
      CALL TRDQO(RT_72,RT_73,RT_74,ISd,ISq,RT_75,Theta,1)

! 780:[sumjct] Summing/Differencing Junctions 
      RT_9 = + RT_11 - UFd

! 790:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_9
      RVD2_1(2) = 0.0
      RT_10 = EMTDC_XPI(0,KpV,TiV,-10000000000.0,10000000000.0,RVD1_1,RV&
     &D2_1)

! 800:[gain] Gain Block 
!  Gain
      RT_13 = wCf_pu * UFq

! 810:[gain] Gain Block 
!  Gain
      RT_12 = wCf_pu * UFd

! 820:[gain] Gain Block 
!  Gain
      RT_15 = wLf_pu * IWq

! 830:[sumjct] Summing/Differencing Junctions 
      Err = + UFqref - UFq

! 840:[gain] Gain Block 
!  Gain
      RT_16 = wLf_pu * IWd

! 850:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = Err
      RVD2_1(2) = 0.0
      RT_7 = EMTDC_XPI(0,KpV,TiV,-10000000000.0,10000000000.0,RVD1_1,RVD&
     &2_1)

! 860:[sumjct] Summing/Differencing Junctions 
      RT_3 = + ISq + RT_7 - RT_12

! 870:[div] Divider 
      IF (ABS(RT_60) .LT. 1.0E-100) THEN
         IF (RT_60 .LT. 0.0)  THEN
            Cbase = -1.0E100 * RT_59
         ELSE
            Cbase =  1.0E100 * RT_59
         ENDIF
      ELSE
         Cbase = RT_59 / RT_60
      ENDIF

! 880:[mult] Multiplier 
      RT_28 = IWd * UFq

! 890:[mult] Multiplier 
      RT_29 = IWq * UFd

! 900:[square] Square 
      RT_82 = IWd * IWd

! 910:[mult] Multiplier 
      RT_30 = IWd * UFd

! 920:[mult] Multiplier 
      RT_31 = UFq * IWq

! 930:[sumjct] Summing/Differencing Junctions 
      RT_4 = + ISd + RT_10 + RT_13

! 940:[Current_Limiter_3_2_2]  
      CALL Current_Limiter_3_2_2Dyn(RT_1, RT_2, RT_3, RT_4, Theta)


! 950:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_1 - IWq

! 960:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_5
      RVD2_1(2) = 0.0
      RT_6 = EMTDC_XPI(0,KpI,TiI,-10000000000.0,10000000000.0,RVD1_1,RVD&
     &2_1)

! 970:[sumjct] Summing/Differencing Junctions 
      Ucq = + UFq + RT_6 - RT_16

! 980:[sumjct] Summing/Differencing Junctions 
      RT_21 = + RT_2 - IWd

! 990:[pi_ctlr] PI Controller \w Interpolation 
      RVD1_1 = RTCF(NRTCF)
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_21
      RVD2_1(2) = 0.0
      RT_14 = EMTDC_XPI(0,KpI,TiI,-10000000000.0,10000000000.0,RVD1_1,RV&
     &D2_1)

! 1000:[sumjct] Summing/Differencing Junctions 
      Ucd = + UFd + RT_14 + RT_15

! 1010:[polar_rec] Polar Rectangular coordinate converter 
      RT_33 = SQRT(Ucd*Ucd+Ucq*Ucq)
      IF ((ABS(Ucd).GT.1.0E-20).OR.(ABS(Ucq).GT.1.0E-20)) THEN
        RT_35 = ATAN2(Ucq,Ucd)
      ELSE
        RT_35 = 0.0
      ENDIF

! 1020:[polar_rec] Polar Rectangular coordinate converter 
      RT_32 = RT_33*COS(RT_35)
      RT_34 = RT_33*SIN(RT_35)

! 1030:[sumjct] Summing/Differencing Junctions 
      RT_25 = + RT_30 + RT_31

! 1040:[sumjct] Summing/Differencing Junctions 
      RT_27 = - RT_28 + RT_29

! 1050:[abcdq0] abc dq0 transformation 
!DQ0 to ABC transformation
      CALL TRDQO(RT_17,RT_18,RT_19,RT_32,RT_34,RT_8,Theta,-1)

! 1060:[polar_rec] Polar Rectangular coordinate converter 
      RT_42 = SQRT(UFd*UFd+UFq*UFq)
      IF ((ABS(UFd).GT.1.0E-20).OR.(ABS(UFq).GT.1.0E-20)) THEN
        RT_41 = ATAN2(UFq,UFd)
      ELSE
        RT_41 = 0.0
      ENDIF

! 1070:[div] Divider 
      IF (ABS(Cbase) .LT. 1.0E-100) THEN
         IF (Cbase .LT. 0.0)  THEN
            RT_62 = -1.0E100 * Cf
         ELSE
            RT_62 =  1.0E100 * Cf
         ENDIF
      ELSE
         RT_62 = Cf / Cbase
      ENDIF

! 1080:[square] Square 
      RT_83 = IWq * IWq

! 1090:[mult] Multiplier 
      RT_24 = RT_25 * RT_22

! 1100:[sumjct] Summing/Differencing Junctions 
      RT_84 = + RT_82 + RT_83

! 1110:[mult] Multiplier 
      RT_26 = RT_27 * RT_23

! 1120:[datamerge] Merges data signals into an array 
      RT_20(1) = RT_17
      RT_20(2) = RT_18
      RT_20(3) = RT_19

! 1130:[sumjct] Summing/Differencing Junctions 
      Delta_Vf = - RT_41 + RT_45

! 1140:[mult] Multiplier 
      RT_61 = RT_62 * RT_63

! 1150:[realpole] Real Pole 
!  Real_Pole
      Pdq = REALPOLE(0,1,0,1.0,0.001,RT_24,0.0,-1.0E20,1.0E20)

! 1160:[sqrt] Square Root 
      LVD1_1 = STORL(NSTORL)
      IF (RT_84 .LT. 0.0) THEN
        Iout = 0.0
        IF (.NOT. LVD1_1) THEN
          CALL EMTDC_MESSAGE(ICALL_NO,955160911,1,2,"A negative value is&
     & detected as an input to the Square Root function. ")
          CALL EMTDC_MESSAGE(ICALL_NO,955160911,1,-1,"Input is treated a&
     &s 0.0.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ELSE
         Iout = SQRT(RT_84)
      ENDIF
      NSTORL = NSTORL + 1

! 1170:[realpole] Real Pole 
!  Real_Pole
      Qdq = REALPOLE(0,1,0,1.0,0.001,RT_26,0.0,-1.0E20,1.0E20)

! 1180:[sumjct] Summing/Differencing Junctions 
      RT_39 = + Theta - Theta_ref

! 1190:[gain] Gain Block 
!  Gain
      Vref = Vbase * RT_20

! 1200:[sumjct] Summing/Differencing Junctions 
      Delta_Vc = - RT_35 + RT_40

! 1210:[sumjct] Summing/Differencing Junctions 
      RT_43 = + Delta_Vc - Delta_Vf

! 1220:[pgb] Output Channel '1'

      PGB(IPGB+1) = RT_61

! 1230:[pgb] Output Channel 'Isq'

      PGB(IPGB+2) = ISq

! 1240:[pgb] Output Channel 'Isd'

      PGB(IPGB+3) = ISd

! 1250:[pgb] Output Channel 'Ufq'

      PGB(IPGB+4) = UFq

! 1260:[pgb] Output Channel 'Ufd'

      PGB(IPGB+5) = UFd

! 1270:[pgb] Output Channel '2'

      PGB(IPGB+6) = wCf_pu

! 1280:[pgb] Output Channel 'Icq'

      PGB(IPGB+7) = IWq

! 1290:[pgb] Output Channel 'Icd'

      PGB(IPGB+8) = IWd

! 1310:[pgb] Output Channel 'Iout'

      PGB(IPGB+9) = Iout

! 1320:[pgb] Output Channel 'P'

      PGB(IPGB+10) = Pdq

! 1340:[pgb] Output Channel 'Q'

      PGB(IPGB+11) = Qdq

! 1350:[pgb] Output Channel 'wt'

      PGB(IPGB+12) = 57.29577951 * Theta_ref

! 1360:[pgb] Output Channel 'Theta_int'

      PGB(IPGB+13) = RT_39

! 1370:[div] Divider 
      IF (ABS(Wrated) .LT. 1.0E-100) THEN
         IF (Wrated .LT. 0.0)  THEN
            Lbase = -1.0E100 * Zbase
         ELSE
            Lbase =  1.0E100 * Zbase
         ENDIF
      ELSE
         Lbase = Zbase / Wrated
      ENDIF

! 1380:[pgb] Output Channel 'erri'

      PGB(IPGB+14) = RT_5

! 1390:[pgb] Output Channel 'errv'

      PGB(IPGB+15) = Err

! 1400:[pgb] Output Channel 'Untitled'

      PGB(IPGB+16) = Zbase

! 1420:[pgb] Output Channel 'id'

      PGB(IPGB+17) = ISd

! 1440:[pgb] Output Channel 'Delta_Vc'

      PGB(IPGB+18) = Delta_Vc

! 1450:[pgb] Output Channel 'Ucq'

      PGB(IPGB+19) = Ucq

! 1460:[pgb] Output Channel 'Ucd'

      PGB(IPGB+20) = Ucd

! 1470:[pgb] Output Channel 'Delta_delta_VfVc'

      PGB(IPGB+21) = RT_43

! 1480:[pgb] Output Channel 'Delta_Vf'

      PGB(IPGB+22) = Delta_Vf

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 13) = W
      STOF(ISTOF + 14) = UFqref
      STOF(ISTOF + 15) = Wgrid
      STOF(ISTOF + 16) = Pdq
      STOF(ISTOF + 17) = Qdq
      STOF(ISTOF + 18) = Wref
      STOF(ISTOF + 19) = VratedLLrms
      STOF(ISTOF + 20) = Iratedphrms
      STOF(ISTOF + 21) = Wrated
      STOF(ISTOF + 22) = Lf
      STOF(ISTOF + 23) = Cf
      STOF(ISTOF + 24) = RT_1
      STOF(ISTOF + 25) = RT_2
      STOF(ISTOF + 26) = RT_3
      STOF(ISTOF + 27) = RT_4
      STOF(ISTOF + 28) = RT_5
      STOF(ISTOF + 29) = RT_6
      STOF(ISTOF + 30) = Err
      STOF(ISTOF + 31) = RT_7
      STOF(ISTOF + 32) = RT_8
      STOF(ISTOF + 33) = RT_9
      STOF(ISTOF + 34) = RT_10
      STOF(ISTOF + 35) = RT_11
      STOF(ISTOF + 36) = RT_12
      STOF(ISTOF + 37) = RT_13
      STOF(ISTOF + 38) = RT_14
      STOF(ISTOF + 39) = RT_15
      STOF(ISTOF + 40) = Ucd
      STOF(ISTOF + 41) = RT_16
      STOF(ISTOF + 42) = Ucq
      STOF(ISTOF + 43) = RT_17
      STOF(ISTOF + 44) = RT_18
      STOF(ISTOF + 45) = RT_19
      STOF(ISTOF + 49) = RT_21
      STOF(ISTOF + 50) = RT_22
      STOF(ISTOF + 51) = RT_23
      STOF(ISTOF + 52) = RT_24
      STOF(ISTOF + 53) = RT_25
      STOF(ISTOF + 54) = RT_26
      STOF(ISTOF + 55) = RT_27
      STOF(ISTOF + 56) = RT_28
      STOF(ISTOF + 57) = RT_29
      STOF(ISTOF + 58) = RT_30
      STOF(ISTOF + 59) = RT_31
      STOF(ISTOF + 60) = RT_32
      STOF(ISTOF + 61) = RT_33
      STOF(ISTOF + 62) = RT_34
      STOF(ISTOF + 63) = RT_35
      STOF(ISTOF + 64) = RT_36
      STOF(ISTOF + 65) = Delta_Vc
      STOF(ISTOF + 66) = RT_37
      STOF(ISTOF + 67) = RT_38
      STOF(ISTOF + 68) = Theta_ref
      STOF(ISTOF + 69) = RT_39
      STOF(ISTOF + 70) = RT_40
      STOF(ISTOF + 71) = RT_41
      STOF(ISTOF + 72) = RT_42
      STOF(ISTOF + 73) = Delta_Vf
      STOF(ISTOF + 74) = RT_43
      STOF(ISTOF + 75) = RT_44
      STOF(ISTOF + 76) = RT_45
      STOF(ISTOF + 77) = RT_46
      STOF(ISTOF + 78) = UFq
      STOF(ISTOF + 79) = UFd
      STOF(ISTOF + 80) = ISq
      STOF(ISTOF + 81) = ISd
      STOF(ISTOF + 82) = Theta
      STOF(ISTOF + 83) = RT_47
      STOF(ISTOF + 84) = RT_48
      STOF(ISTOF + 85) = RT_49
      STOF(ISTOF + 86) = RT_50
      STOF(ISTOF + 93) = Vbase
      STOF(ISTOF + 97) = Ibase
      STOF(ISTOF + 98) = RT_54
      STOF(ISTOF + 99) = RT_55
      STOF(ISTOF + 100) = RT_56
      STOF(ISTOF + 101) = RT_57
      STOF(ISTOF + 102) = RT_58
      STOF(ISTOF + 103) = MVAbase
      STOF(ISTOF + 104) = wLf_pu
      STOF(ISTOF + 105) = RT_59
      STOF(ISTOF + 106) = RT_60
      STOF(ISTOF + 107) = wCf_pu
      STOF(ISTOF + 108) = Zbase
      STOF(ISTOF + 109) = RT_61
      STOF(ISTOF + 110) = RT_62
      STOF(ISTOF + 111) = Cbase
      STOF(ISTOF + 112) = RT_63
      STOF(ISTOF + 113) = RT_64
      STOF(ISTOF + 114) = RT_65
      STOF(ISTOF + 115) = RT_66
      STOF(ISTOF + 116) = RT_67
      STOF(ISTOF + 117) = RT_68
      STOF(ISTOF + 118) = RT_69
      STOF(ISTOF + 119) = RT_70
      STOF(ISTOF + 120) = RT_71
      STOF(ISTOF + 121) = RT_72
      STOF(ISTOF + 122) = RT_73
      STOF(ISTOF + 123) = RT_74
      STOF(ISTOF + 124) = RT_75
      STOF(ISTOF + 125) = KpI
      STOF(ISTOF + 126) = TiI
      STOF(ISTOF + 127) = RT_76
      STOF(ISTOF + 128) = RT_77
      STOF(ISTOF + 129) = KpV
      STOF(ISTOF + 130) = RT_78
      STOF(ISTOF + 131) = RT_79
      STOF(ISTOF + 132) = TiV
      STOF(ISTOF + 133) = RT_80
      STOF(ISTOF + 134) = RT_81
      STOF(ISTOF + 135) = RT_82
      STOF(ISTOF + 136) = RT_83
      STOF(ISTOF + 137) = RT_84
      STOF(ISTOF + 138) = Iout
      STOF(ISTOF + 139) = IWd
      STOF(ISTOF + 140) = IWq
      STOF(ISTOF + 141) = Lbase

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Vref(IT_0)
         STOF(ISTOF + 3 + IT_0) = Igrid(IT_0)
         STOF(ISTOF + 6 + IT_0) = Vgrid(IT_0)
         STOF(ISTOF + 9 + IT_0) = I_inv(IT_0)
         STOF(ISTOF + 45 + IT_0) = RT_20(IT_0)
         STOF(ISTOF + 86 + IT_0) = RT_51(IT_0)
         STOF(ISTOF + 89 + IT_0) = RT_52(IT_0)
         STOF(ISTOF + 93 + IT_0) = RT_53(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Vref     is output
      !Wgrid    is output
      !Pdq      is output
      !Qdq      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE VF_Control_7_2_2Out()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Current_Limiter_3_2_2Out  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_8, RT_11, RT_22, RT_23, RT_36
      REAL     RT_37, RT_40, RT_44, RT_45, RT_46
      REAL     RT_47, RT_49, RT_50, RT_57, RT_59
      REAL     RT_63, KpI, RT_76, RT_77, KpV
      REAL     RT_78, RT_79, RT_80, RT_81

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 22
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_8     = STOF(ISTOF + 32)
      RT_11    = STOF(ISTOF + 35)
      RT_22    = STOF(ISTOF + 50)
      RT_23    = STOF(ISTOF + 51)
      RT_36    = STOF(ISTOF + 64)
      RT_37    = STOF(ISTOF + 66)
      RT_40    = STOF(ISTOF + 70)
      RT_44    = STOF(ISTOF + 75)
      RT_45    = STOF(ISTOF + 76)
      RT_46    = STOF(ISTOF + 77)
      RT_47    = STOF(ISTOF + 83)
      RT_49    = STOF(ISTOF + 85)
      RT_50    = STOF(ISTOF + 86)
      RT_57    = STOF(ISTOF + 101)
      RT_59    = STOF(ISTOF + 105)
      RT_63    = STOF(ISTOF + 112)
      KpI      = STOF(ISTOF + 125)
      RT_76    = STOF(ISTOF + 127)
      RT_77    = STOF(ISTOF + 128)
      KpV      = STOF(ISTOF + 129)
      RT_78    = STOF(ISTOF + 130)
      RT_79    = STOF(ISTOF + 131)
      RT_80    = STOF(ISTOF + 133)
      RT_81    = STOF(ISTOF + 134)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'VF_Control_7_2_2.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[emtconst] Commonly Used Constants (pi...) 
      RT_45 = PI_BY2

! 30:[const] Real Constant 

      RT_36 = 0.0

! 40:[const] Real Constant 

      RT_81 = 0.0

! 70:[const] Real Constant 

      RT_44 = 0.0

! 90:[const] Real Constant 

      RT_8 = 0.0

! 110:[const] Real Constant 

      RT_46 = 0.0

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_40 = PI_BY2

! 130:[const] Real Constant 

      RT_11 = 0.0

! 180:[emtconst] Commonly Used Constants (pi...) 
      RT_50 = SQRT_3

! 190:[emtconst] Commonly Used Constants (pi...) 
      RT_49 = SQRT_2

! 200:[const] Real Constant 

      RT_80 = 1.0

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_47 = SQRT_2

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_37 = TWO_PI

! 280:[const] Real Constant 

      RT_59 = 1.0

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_57 = SQRT_3

! 320:[const] Real Constant 

      KpI = 5.0

! 330:[const] Real Constant 

      RT_23 = 1.0

! 340:[const] Real Constant 

      KpV = 1.0

! 350:[const] Real Constant 

      RT_76 = 1.0

! 360:[const] Real Constant 

      RT_79 = 1.0

! 370:[const] Real Constant 

      RT_77 = 5.0

! 380:[const] Real Constant 

      RT_78 = 10.0

! 390:[const] Real Constant 

      RT_22 = 1.0

! 430:[const] Real Constant 

      RT_63 = 1.0

! 940:[Current_Limiter_3_2_2]  
      CALL Current_Limiter_3_2_2Out()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 32) = RT_8
      STOF(ISTOF + 35) = RT_11
      STOF(ISTOF + 50) = RT_22
      STOF(ISTOF + 51) = RT_23
      STOF(ISTOF + 64) = RT_36
      STOF(ISTOF + 66) = RT_37
      STOF(ISTOF + 70) = RT_40
      STOF(ISTOF + 75) = RT_44
      STOF(ISTOF + 76) = RT_45
      STOF(ISTOF + 77) = RT_46
      STOF(ISTOF + 83) = RT_47
      STOF(ISTOF + 85) = RT_49
      STOF(ISTOF + 86) = RT_50
      STOF(ISTOF + 101) = RT_57
      STOF(ISTOF + 105) = RT_59
      STOF(ISTOF + 112) = RT_63
      STOF(ISTOF + 125) = KpI
      STOF(ISTOF + 127) = RT_76
      STOF(ISTOF + 128) = RT_77
      STOF(ISTOF + 129) = KpV
      STOF(ISTOF + 130) = RT_78
      STOF(ISTOF + 131) = RT_79
      STOF(ISTOF + 133) = RT_80
      STOF(ISTOF + 134) = RT_81


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE VF_Control_7_2_2Dyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Current_Limiter_3_2_2Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_8, RT_11, RT_22, RT_23, RT_36
      REAL     RT_37, RT_40, RT_44, RT_45, RT_46
      REAL     RT_47, RT_49, RT_50, RT_57, RT_59
      REAL     RT_63, KpI, RT_76, RT_77, KpV
      REAL     RT_78, RT_79, RT_80, RT_81

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[emtconst] Commonly Used Constants (pi...) 
      RT_45 = PI_BY2

! 30:[const] Real Constant 
      RT_36 = 0.0

! 40:[const] Real Constant 
      RT_81 = 0.0

! 70:[const] Real Constant 
      RT_44 = 0.0

! 90:[const] Real Constant 
      RT_8 = 0.0

! 110:[const] Real Constant 
      RT_46 = 0.0

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_40 = PI_BY2

! 130:[const] Real Constant 
      RT_11 = 0.0

! 180:[emtconst] Commonly Used Constants (pi...) 
      RT_50 = SQRT_3

! 190:[emtconst] Commonly Used Constants (pi...) 
      RT_49 = SQRT_2

! 200:[const] Real Constant 
      RT_80 = 1.0

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_47 = SQRT_2

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_37 = TWO_PI

! 280:[const] Real Constant 
      RT_59 = 1.0

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_57 = SQRT_3

! 320:[const] Real Constant 
      KpI = 5.0

! 330:[const] Real Constant 
      RT_23 = 1.0

! 340:[const] Real Constant 
      KpV = 1.0

! 350:[const] Real Constant 
      RT_76 = 1.0

! 360:[const] Real Constant 
      RT_79 = 1.0

! 370:[const] Real Constant 
      RT_77 = 5.0

! 380:[const] Real Constant 
      RT_78 = 10.0

! 390:[const] Real Constant 
      RT_22 = 1.0

! 430:[const] Real Constant 
      RT_63 = 1.0

! 450:[gain] Gain Block 

! 460:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 470:[div] Divider 

! 480:[mult] Multiplier 

! 490:[square] Square 

! 500:[mult] Multiplier 

! 510:[mult] Multiplier 

! 520:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 530:[mult] Multiplier 

! 540:[mult] Multiplier 

! 550:[div] Divider 

! 560:[div] Divider 

! 570:[gain] Gain Block 

! 580:[gain] Gain Block 

! 590:[div] Divider 

! 600:[datatap] Scalar/Array Tap 

! 610:[datatap] Scalar/Array Tap 

! 620:[datatap] Scalar/Array Tap 

! 630:[div] Divider 

! 640:[datatap] Scalar/Array Tap 

! 650:[datatap] Scalar/Array Tap 

! 660:[datatap] Scalar/Array Tap 

! 670:[div] Divider 

! 680:[datatap] Scalar/Array Tap 

! 690:[datatap] Scalar/Array Tap 

! 700:[datatap] Scalar/Array Tap 

! 710:[div] Divider 

! 720:[mult] Multiplier 

! 730:[div] Divider 

! 740:[mult] Multiplier 

! 750:[abcdq0] abc dq0 transformation 

! 760:[abcdq0] abc dq0 transformation 

! 770:[abcdq0] abc dq0 transformation 

! 780:[sumjct] Summing/Differencing Junctions 

! 790:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 800:[gain] Gain Block 

! 810:[gain] Gain Block 

! 820:[gain] Gain Block 

! 830:[sumjct] Summing/Differencing Junctions 

! 840:[gain] Gain Block 

! 850:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 860:[sumjct] Summing/Differencing Junctions 

! 870:[div] Divider 

! 880:[mult] Multiplier 

! 890:[mult] Multiplier 

! 900:[square] Square 

! 910:[mult] Multiplier 

! 920:[mult] Multiplier 

! 930:[sumjct] Summing/Differencing Junctions 

! 940:[Current_Limiter_3_2_2]  
      CALL Current_Limiter_3_2_2Dyn_Begin()


! 950:[sumjct] Summing/Differencing Junctions 

! 960:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 970:[sumjct] Summing/Differencing Junctions 

! 980:[sumjct] Summing/Differencing Junctions 

! 990:[pi_ctlr] PI Controller \w Interpolation 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 1000:[sumjct] Summing/Differencing Junctions 

! 1010:[polar_rec] Polar Rectangular coordinate converter 

! 1020:[polar_rec] Polar Rectangular coordinate converter 

! 1030:[sumjct] Summing/Differencing Junctions 

! 1040:[sumjct] Summing/Differencing Junctions 

! 1050:[abcdq0] abc dq0 transformation 

! 1060:[polar_rec] Polar Rectangular coordinate converter 

! 1070:[div] Divider 

! 1080:[square] Square 

! 1090:[mult] Multiplier 

! 1100:[sumjct] Summing/Differencing Junctions 

! 1110:[mult] Multiplier 

! 1120:[datamerge] Merges data signals into an array 

! 1130:[sumjct] Summing/Differencing Junctions 

! 1140:[mult] Multiplier 

! 1150:[realpole] Real Pole 

! 1160:[sqrt] Square Root 

! 1170:[realpole] Real Pole 

! 1180:[sumjct] Summing/Differencing Junctions 

! 1190:[gain] Gain Block 

! 1200:[sumjct] Summing/Differencing Junctions 

! 1210:[sumjct] Summing/Differencing Junctions 

! 1220:[pgb] Output Channel '1'

! 1230:[pgb] Output Channel 'Isq'

! 1240:[pgb] Output Channel 'Isd'

! 1250:[pgb] Output Channel 'Ufq'

! 1260:[pgb] Output Channel 'Ufd'

! 1270:[pgb] Output Channel '2'

! 1280:[pgb] Output Channel 'Icq'

! 1290:[pgb] Output Channel 'Icd'

! 1310:[pgb] Output Channel 'Iout'

! 1320:[pgb] Output Channel 'P'

! 1340:[pgb] Output Channel 'Q'

! 1350:[pgb] Output Channel 'wt'

! 1360:[pgb] Output Channel 'Theta_int'

! 1370:[div] Divider 

! 1380:[pgb] Output Channel 'erri'

! 1390:[pgb] Output Channel 'errv'

! 1400:[pgb] Output Channel 'Untitled'

! 1420:[pgb] Output Channel 'id'

! 1440:[pgb] Output Channel 'Delta_Vc'

! 1450:[pgb] Output Channel 'Ucq'

! 1460:[pgb] Output Channel 'Ucd'

! 1470:[pgb] Output Channel 'Delta_delta_VfVc'

! 1480:[pgb] Output Channel 'Delta_Vf'

      RETURN
      END

!=======================================================================

      SUBROUTINE VF_Control_7_2_2Out_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Current_Limiter_3_2_2Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_8, RT_11, RT_22, RT_23, RT_36
      REAL     RT_37, RT_40, RT_44, RT_45, RT_46
      REAL     RT_47, RT_49, RT_50, RT_57, RT_59
      REAL     RT_63, KpI, RT_76, RT_77, KpV
      REAL     RT_78, RT_79, RT_80, RT_81

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[emtconst] Commonly Used Constants (pi...) 
      RT_45 = PI_BY2

! 30:[const] Real Constant 
      RT_36 = 0.0

! 40:[const] Real Constant 
      RT_81 = 0.0

! 70:[const] Real Constant 
      RT_44 = 0.0

! 90:[const] Real Constant 
      RT_8 = 0.0

! 110:[const] Real Constant 
      RT_46 = 0.0

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_40 = PI_BY2

! 130:[const] Real Constant 
      RT_11 = 0.0

! 180:[emtconst] Commonly Used Constants (pi...) 
      RT_50 = SQRT_3

! 190:[emtconst] Commonly Used Constants (pi...) 
      RT_49 = SQRT_2

! 200:[const] Real Constant 
      RT_80 = 1.0

! 230:[emtconst] Commonly Used Constants (pi...) 
      RT_47 = SQRT_2

! 250:[emtconst] Commonly Used Constants (pi...) 
      RT_37 = TWO_PI

! 280:[const] Real Constant 
      RT_59 = 1.0

! 300:[emtconst] Commonly Used Constants (pi...) 
      RT_57 = SQRT_3

! 320:[const] Real Constant 
      KpI = 5.0

! 330:[const] Real Constant 
      RT_23 = 1.0

! 340:[const] Real Constant 
      KpV = 1.0

! 350:[const] Real Constant 
      RT_76 = 1.0

! 360:[const] Real Constant 
      RT_79 = 1.0

! 370:[const] Real Constant 
      RT_77 = 5.0

! 380:[const] Real Constant 
      RT_78 = 10.0

! 390:[const] Real Constant 
      RT_22 = 1.0

! 430:[const] Real Constant 
      RT_63 = 1.0

! 940:[Current_Limiter_3_2_2]  
      CALL Current_Limiter_3_2_2Out_Begin()


      RETURN
      END

